### PR TITLE
Binary added.

### PR DESCRIPTION
**Pull request by xtreeguy**
There were no binary for the npm package. I added it.
After the next push into the npm repository all should work!

### CODE REVIEW

**Comment by xtreeguy** [comment]
Closing this pull request to split in two.

**Comment by xtreeguy** [comment]
Reopened this pull request because GitHub do not allow to create the pull request for specific commit.

**Comment by xtreeguy** [comment]
I added small typo fix (with missing space char) too.

**Comment by fpereiro** [comment]
Hello xtreeguy,

First of all, thank you so much for your thoughtful and useful contributions!

I merged both your changes. I took the liberty of modifying the spacing on bin/clit to quell my OCD.

I will publish the changes to npm shortly.

Also, if you are interested, please give me your name and/or email address, and I will add you as a contributor to the library on the package.json

Once again, thank you very much for your contribution!

**Comment by xtreeguy** [comment]
Thank you, too.
I am also glad that my contribution has been accepted and appreciated. 
I think that it does not necessarily add me to the contributors. The main thing that changes already on npmjs.org and I can upgrade my own installation now. 
Thank you for this utility. If not for you, I would write something like that.

**Comment by fpereiro** [comment]
Thank you for your kind words. I would really like to add you to the contributors list. Let me know if you are interested.

Cheers!

**Pull request merged**
